<?php

use Illuminate\Database\Seeder;
use App\Article;

class ArticlesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $article1 = new Article();
        $article1->title = 'Article 1';
        $article1->url = 'article1';
        $article1->images = 'article1.png';
        $article1->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article1->category_id = 1;
        $article1->seo_id = 7;
        $article1->slide = 1;
        $article1->status = 1;
        $article1->user_id = 1;
        $article1->save();

        $article2 = new Article();
        $article2->title = 'Article 2';
        $article2->url = 'article2';
        $article2->images = 'article2.png';
        $article2->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article2->category_id = 1;
        $article2->seo_id = 7;
        $article2->slide = 0;
        $article2->status = 1;
        $article2->user_id = 1;
        $article2->save();

        $article3 = new Article();
        $article3->title = 'Article 3';
        $article3->url = 'article3';
        $article3->images = 'article3.png';
        $article3->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article3->category_id = 1;
        $article3->seo_id = 7;
        $article3->slide = 0;
        $article3->status = 1;
        $article3->user_id = 1;
        $article3->save();

        $article4 = new Article();
        $article4->title = 'Article 4';
        $article4->url = 'article4';
        $article4->images = 'article4.png';
        $article4->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article4->category_id = 1;
        $article4->seo_id = 7;
        $article4->slide = 0;
        $article4->status = 1;
        $article4->user_id = 1;
        $article4->save();

        $article5 = new Article();
        $article5->title = 'Article 5';
        $article5->url = 'article5';
        $article5->images = 'article5.png';
        $article5->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article5->category_id = 1;
        $article5->seo_id = 7;
        $article5->slide = 0;
        $article5->status = 1;
        $article5->user_id = 1;
        $article5->save();

        $article6 = new Article();
        $article6->title = 'Article 6';
        $article6->url = 'article6';
        $article6->images = 'article6.png';
        $article6->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article6->category_id = 2;
        $article6->seo_id = 7;
        $article6->slide = 1;
        $article6->status = 1;
        $article6->user_id = 1;
        $article6->save();

        $article7 = new Article();
        $article7->title = 'Article 7';
        $article7->url = 'article7';
        $article7->images = 'article7.png';
        $article7->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article7->category_id = 2;
        $article7->seo_id = 7;
        $article7->slide = 0;
        $article7->status = 1;
        $article7->user_id = 1;
        $article7->save();

        $article8 = new Article();
        $article8->title = 'Article 8';
        $article8->url = 'article8';
        $article8->images = 'article8.png';
        $article8->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article8->category_id = 2;
        $article8->seo_id = 7;
        $article8->slide = 0;
        $article8->status = 1;
        $article8->user_id = 1;
        $article8->save();

        $article9 = new Article();
        $article9->title = 'Article 9';
        $article9->url = 'article9';
        $article9->images = 'article9.png';
        $article9->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article9->category_id = 2;
        $article9->seo_id = 7;
        $article9->slide = 0;
        $article9->status = 1;
        $article9->user_id = 1;
        $article9->save();

        $article10 = new Article();
        $article10->title = 'Article 10';
        $article10->url = 'article10';
        $article10->images = 'article10.png';
        $article10->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article10->category_id = 2;
        $article10->seo_id = 7;
        $article10->slide = 0;
        $article10->status = 1;
        $article10->user_id = 1;
        $article10->save();

        $article11 = new Article();
        $article11->title = 'Article 11';
        $article11->url = 'article11';
        $article11->images = 'article11.png';
        $article11->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article11->category_id = 3;
        $article11->seo_id = 7;
        $article11->slide = 1;
        $article11->status = 1;
        $article11->user_id = 1;
        $article11->save();

        $article12 = new Article();
        $article12->title = 'Article 12';
        $article12->url = 'article12';
        $article12->images = 'article12.png';
        $article12->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article12->category_id = 3;
        $article12->seo_id = 7;
        $article12->slide = 0;
        $article12->status = 1;
        $article12->user_id = 1;
        $article12->save();

        $article13 = new Article();
        $article13->title = 'Article 13';
        $article13->url = 'article13';
        $article13->images = 'article13.png';
        $article13->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article13->category_id = 3;
        $article13->seo_id = 7;
        $article13->slide = 0;
        $article13->status = 1;
        $article13->user_id = 1;
        $article13->save();

        $article14 = new Article();
        $article14->title = 'Article 14';
        $article14->url = 'article14';
        $article14->images = 'article14.png';
        $article14->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article14->category_id = 3;
        $article14->seo_id = 7;
        $article14->slide = 0;
        $article14->status = 1;
        $article14->user_id = 1;
        $article14->save();

        $article15 = new Article();
        $article15->title = 'Article 15';
        $article15->url = 'article15';
        $article15->images = 'article15.png';
        $article15->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article15->category_id = 3;
        $article15->seo_id = 7;
        $article15->slide = 0;
        $article15->status = 1;
        $article15->user_id = 1;
        $article15->save();

        $article16 = new Article();
        $article16->title = 'Article 16';
        $article16->url = 'article16';
        $article16->images = 'article16.png';
        $article16->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article16->category_id = 4;
        $article16->seo_id = 7;
        $article16->slide = 0;
        $article16->status = 1;
        $article16->user_id = 1;
        $article16->save();

        $article17 = new Article();
        $article17->title = 'Article 17';
        $article17->url = 'article17';
        $article17->images = 'article17.png';
        $article17->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article17->category_id = 4;
        $article17->seo_id = 7;
        $article17->slide = 0;
        $article17->status = 1;
        $article17->user_id = 1;
        $article17->save();

        $article18 = new Article();
        $article18->title = 'Article 18';
        $article18->url = 'article18';
        $article18->images = 'article18.png';
        $article18->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article18->category_id = 4;
        $article18->seo_id = 7;
        $article18->slide = 0;
        $article18->status = 1;
        $article18->user_id = 1;
        $article18->save();

        $article19 = new Article();
        $article19->title = 'Article 19';
        $article19->url = 'article19';
        $article19->images = 'article19.png';
        $article19->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article19->category_id = 4;
        $article19->seo_id = 7;
        $article19->slide = 0;
        $article19->status = 1;
        $article19->user_id = 1;
        $article19->save();

        $article20 = new Article();
        $article20->title = 'Article 20';
        $article20->url = 'article20';
        $article20->images = 'article20.png';
        $article20->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article20->category_id = 4;
        $article20->seo_id = 7;
        $article20->slide = 0;
        $article20->status = 1;
        $article20->user_id = 1;
        $article20->save();

        $article21 = new Article();
        $article21->title = 'Article 21';
        $article21->url = 'article21';
        $article21->images = 'article21.png';
        $article21->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article21->category_id = 5;
        $article21->seo_id = 7;
        $article21->slide = 0;
        $article21->status = 1;
        $article21->user_id = 1;
        $article21->save();

        $article22 = new Article();
        $article22->title = 'Article 22';
        $article22->url = 'article22';
        $article22->images = 'article22.png';
        $article22->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article22->category_id = 5;
        $article22->seo_id = 7;
        $article22->slide = 0;
        $article22->status = 1;
        $article22->user_id = 1;
        $article22->save();

        $article23 = new Article();
        $article23->title = 'Article 23';
        $article23->url = 'article23';
        $article23->images = 'article23.png';
        $article23->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article23->category_id = 5;
        $article23->seo_id = 7;
        $article23->slide = 0;
        $article23->status = 1;
        $article23->user_id = 1;
        $article23->save();

        $article24 = new Article();
        $article24->title = 'Article 24';
        $article24->url = 'article24';
        $article24->images = 'article24.png';
        $article24->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article24->category_id = 5;
        $article24->seo_id = 7;
        $article24->slide = 0;
        $article24->status = 1;
        $article24->user_id = 1;
        $article24->save();

        $article25 = new Article();
        $article25->title = 'Article 25';
        $article25->url = 'article25';
        $article25->images = 'article25.png';
        $article25->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article25->category_id = 5;
        $article25->seo_id = 7;
        $article25->slide = 0;
        $article25->status = 1;
        $article25->user_id = 1;
        $article25->save();

        $article26 = new Article();
        $article26->title = 'Article 26';
        $article26->url = 'article26';
        $article26->images = 'article26.png';
        $article26->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article26->category_id = 6;
        $article26->seo_id = 7;
        $article26->slide = 0;
        $article26->status = 1;
        $article26->user_id = 1;
        $article26->save();

        $article27 = new Article();
        $article27->title = 'Article 27';
        $article27->url = 'article27';
        $article27->images = 'article27.png';
        $article27->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article27->category_id = 6;
        $article27->seo_id = 7;
        $article27->slide = 0;
        $article27->status = 1;
        $article27->user_id = 1;
        $article27->save();

        $article28 = new Article();
        $article28->title = 'Article 28';
        $article28->url = 'article28';
        $article28->images = 'article28.png';
        $article28->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article28->category_id = 6;
        $article28->seo_id = 7;
        $article28->slide = 0;
        $article28->status = 1;
        $article28->user_id = 1;
        $article28->save();

        $article29 = new Article();
        $article29->title = 'Article 29';
        $article29->url = 'article29';
        $article29->images = 'article29.png';
        $article29->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article29->category_id = 6;
        $article29->seo_id = 7;
        $article29->slide = 0;
        $article29->status = 1;
        $article29->user_id = 1;
        $article29->save();

        $article30 = new Article();
        $article30->title = 'Article 30';
        $article30->url = 'article30';
        $article30->images = 'article30.png';
        $article30->text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae orci pellentesque, egestas dui nec, ultricies velit. Donec rutrum quis risus eget eleifend. In sed risus lacus. Integer at posuere nunc, quis lobortis enim. Duis in arcu id magna rutrum mattis. Fusce vulputate nisl eget nibh laoreet feugiat. Fusce posuere velit vel magna eleifend, ac sollicitudin leo laoreet. Fusce vel ante vitae dolor sodales dapibus ut vel dolor. Donec ac sagittis nisl, quis posuere justo. Donec cursus dolor efficitur massa vulputate laoreet. Suspendisse quis justo et metus pretium scelerisque. Etiam varius, magna quis scelerisque molestie, ipsum risus tempor mi, quis lacinia odio lectus quis est. Pellentesque neque neque, pellentesque sit amet lectus ac, sollicitudin lobortis purus. Vestibulum convallis est orci, et volutpat nunc varius vel. Maecenas vel sagittis massa. Proin egestas tellus vitae ante aliquam faucibus eget nec neque. Vivamus vitae nisi eu tellus tristique gravida sit amet at ligula. Vestibulum eu commodo nunc. Nam eget lectus a turpis iaculis accumsan. Cras at est quis mi semper fermentum id ac lectus. Nunc ut sapien semper diam gravida efficitur. In volutpat tortor ipsum, porta faucibus dolor lacinia eu. Donec tincidunt, nulla et rhoncus dictum, quam mauris fermentum dolor, nec malesuada risus tellus vel odio. Suspendisse luctus tincidunt risus, vitae consectetur neque venenatis eu. Fusce sed egestas turpis. Vivamus luctus nulla eget pellentesque maximus. Mauris tincidunt tellus ut sapien consectetur, vehicula cursus ex fermentum. Sed eu venenatis lectus, non mollis ex. Aliquam gravida vel ante sit amet maximus. Donec ultrices velit quis enim venenatis suscipit. Sed ullamcorper, ante eget congue iaculis, libero ligula dignissim sem, ac commodo mauris erat a nunc. In sodales nibh vel purus facilisis egestas. Nulla enim massa, porta pellentesque nisl non, scelerisque eleifend ante. Mauris tortor lectus, blandit malesuada tempor commodo, sagittis ac justo. Pellentesque convallis sagittis pretium. Ut suscipit egestas mauris vel placerat. Ut pellentesque molestie volutpat. Etiam pretium semper ligula non mollis. Quisque faucibus mi dolor, ut euismod urna elementum id. Curabitur vel eros non dui pharetra viverra at nec tellus. Donec convallis commodo tortor, vel pharetra tellus facilisis ac. Nulla convallis ultrices nisi at scelerisque. Cras pellentesque enim et erat placerat vehicula. Morbi libero eros, pretium id arcu sit amet, dictum laoreet sapien. Proin tempus libero sit amet pellentesque hendrerit. In fermentum ligula arcu, ac tempor elit sodales ac. Nullam malesuada purus vitae sapien elementum, vulputate ultrices ipsum laoreet. Integer lacinia augue leo, id consequat nibh cursus ut. Aenean vel cursus ipsum. Nam quis mattis eros.</p>';
        $article30->category_id = 6;
        $article30->seo_id = 7;
        $article30->slide = 0;
        $article30->status = 1;
        $article30->user_id = 1;
        $article30->save();
    }
}
